name: PunishManager
version: '${project.version}'
author: Shizoukia
main: catmoe.shizoukia.punishalertforspigot.PunishAlertForSpigot
commands:
  punishalert:
    description: e
  wipealert:
    description: e